name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  name: publish 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt install libdbus-1-dev pkg-config
      name: Install dbus utils
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: dry run
      uses: actions-rs/cargo@v1
      with:
        command: package
    - name: login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_API_TOKEN}}
    - name: publish
      uses: actions-rs/cargo@v1
      with: 
        command: publish