name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

job:
  name: Publish 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install dbus utils
      run: |
        sudo apt install libdbus-1-dev pkg-config
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Install cargo-release
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-release
    - name: Check packaging
      uses: actions-rs/cargo@v1
      with:
        command: release 
    - name: Login crates.io
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_API_TOKEN}}
    - name: Publish
      uses: actions-rs/cargo@v1
      with: 
        command: release --execute 