on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main

name: CI

jobs:
  job:
    name: Check PR title for CC
    runs-on: ubuntu-latest
    steps:
      - name: Check for CC
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0

  job:
    name: check & test 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libdbus-1-dev pkg-config
        name: Install dbus utils
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  job:
    name: clippy & fmt check 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libdbus-1-dev pkg-config
        name: Install dbus utils
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check