on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main

name: CI

jobs:
  ci:
    name: check & test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libdbus-1-dev pkg-config
        name: Install dbus utils
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable 
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: bltui
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  pkgbuild:
    runs-on: ubuntu-latest
    container: 
      image: archlinux
      # options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Build arch package
        run: |
          mkdir temp_folder
          cp -r src temp_folder
          cp Cargo.* temp_folder
          makepkg -g